version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dio
      - MONGO_INITDB_ROOT_PASSWORD=dio
    ports:
      - "27017:27017"
    volumes:
      - /E:/Desenvolvimento/DIOCursos/Bootcamp_Eduzz/016_introducao_mongo_bd_nosql/introducao_mongo_instalacao/:data/db
